### PR TITLE
add openshift-applier

### PR DESCRIPTION
**Pull request by sherl0cks**
This PR adds automation approach that we use heavily at the Open Innovation Labs to teach infrastructure as code. I'm sharing it as we'll use some version of this to consume the work in this github org, and we'd like to collaborate if it makes sense.

Open to changes / suggestions / doc improvements.

### CODE REVIEW

**Comment by goern** [comment]
very nice work, thx!

**Comment by GrahamDumpleton** [comment]
Not sure I totally understand what this is for. Is it something that would be better off in its own repository?

Also, doesn't the way it handles creation of the service account mean it will only work if done in a project called ``jupyterhub``?

**Comment by sherl0cks** [comment]
> Not sure I totally understand what this is for. Is it something that would be better off in its own repository?

Yes, It could live in it's own repo if you want it to. That's how https://github.com/rht-labs/labs-ci-cd works for us. I was sharing here as a FYI in the event that a fully automated / ansible install for this repo was of interest. Do close this if it is not.

> Also, doesn't the way it handles creation of the service account mean it will only work if done in a project called jupyterhub?

Currently, yes. It could be made to be a template and configurable if so desired. This was quick and dirty.

**Comment by GrahamDumpleton** [comment]
I will close this without merging then. Can revisit later when understand what role it provides and whether is something of general interest with potential users.

**Pull request closed without merging**
